### ISSUE TITLE
item中如何全屏

### ISSUE THREAD

**Issue by Anayuta** [jiajunhui/XPlayer#1]

**Comment by jiajunhui** [comment]
对于做类似于今日头条的item中的视频无缝切换到全屏。这个框架不太好处理。需要单独的轻量处理，我写过类似的demo，方案就是采用一个全局的解码器，通过setDisplay进行切换渲染视图，这样就可以做到页面切换后直接全屏继续播放。

**Comment by Anayuta** [comment]
对的，现在item中就是做不到无缝切换。可以看看你基于你这个框架写的切换demo么？

**Comment by jiajunhui** [comment]
不建议用这个框架做这个需求。本身设计这个框架的时候并未考虑到这种问题。切换渲染视图需要对框架基类进行更改，代价有点高。我之前写的demo是基于MediaPlayer配合SurfaceView做的。

**Comment by Anayuta** [comment]
唉，目前已经接入进去了。后面来改吧

**Comment by jiajunhui** [comment]
你加下我QQ说吧。

**Comment by jiajunhui** [comment]
309812983，加下我QQ吧

**Comment by Anayuta** [comment]
好的
